//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Entitás.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//




public abstract class Entitás {
	private Aszteroidaöv jatekosok;
	private Aszteroida aszteroida;
	public abstract void Mozgas(Szomszéd a);
	public void Furas() {
	}
	
	public abstract void Halal();
	
	public abstract void Felrobban();
	
	public abstract void Lep();
}
