//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Robot.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//




public class Robot extends Entitás {
	public void Mozgas(Szomszéd a) {
	}
	
	public void Felrobban() {
	}
	
	public void Halal() {
	}
	
	public void Lep() {
	}
	
	public void Mozgas(Szomszéd a) {
	}
	
	public void Halal() {
	}
	
	public void Felrobban() {
	}
	
	public void Lep() {
	}
}
