//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Szomszéd.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//




public abstract class Szomszéd {
	public abstract void Robban();
	public abstract void Befogad(Entitás a);
}
