//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Teleportkapu.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//




public class Teleportkapu extends Szomszéd {
	private Aszteroida aszteroida;
	private Teleportkapu parja;
	private Telepes kapuk;
	public Aszteroida ParHelye() {
	}
	
	public void Robban() {
	}
	
	public void Befogad(Entitás a) {
	}
	
	public void Robban() {
	}
	
	public void Befogad(Entitás a) {
	}
}
