//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Útmutató.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//




public class Útmutató {
	private Nyersanyag hozzavalok;
	private Nyersanyag megvanLista;
	public boolean MindMegvan(Nyersanyag ny) {
	}
}
