package szkeleton.game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Aszteroidaöv.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//

import java.util.List;
import java.util.Scanner;

public class Aszteroidaöv {
	private List<Aszteroida> aszteroidak;
	private List<Entitás> jatekosok;
	
	public Aszteroidaöv() {
		Main.printer.print("[" + this + ".Aszteroidaöv()]");
	}
	
	public void DoNapvihar() {
		Main.printer.print("[" + this + ".DoNapvihar()]");
		Main.printer.inc();
		Main.printer.print(">Letrejon napvihar? ('i' = igaz, 'h' = hamis)");
		Scanner in = new Scanner(System.in);
		String answer = in.nextLine();
		Main.printer.print(">Ertek: " + answer);
		if(answer.equals("i")) {
			Main.printer.inc();
			aszteroidak.get(1).Napvihar();
		}
		else
			Main.printer.print(">Nem jott letre napvihar");
		in.close();
	}
	
	public void MinuszAszteroida(Aszteroida a) {
	}
	
	public void AddAszteroida(Aszteroida a) {
		aszteroidak.add(a);
	}
	
	public void AddJatekos(Entitás e) {
		jatekosok.add(e);
	}
}
