package szkeleton.game;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Scanner;

import szkeleton.game.Main;

//
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Aszteroida.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//




public class Aszteroida extends Szomszéd {
	private int kopenyVastagsag;
	private List<Teleportkapu> kapuk;
	private List<Entitás> entitasok;
	private List<Szomszéd> szomszedok;
	private Nyersanyag belsoAnyag;
	private boolean napkozel;
	
	public Aszteroida() {
		Main.printer.print("[" + this + ".Aszteroida()]");
		kapuk=new ArrayList<Teleportkapu>();
		entitasok=new ArrayList <Entitás>();
		szomszedok=new ArrayList <Szomszéd>();
		napkozel = false;
	}
	
	public void SetAnyag(Nyersanyag n) {
		belsoAnyag= n;
		Main.printer.print("["+this+"].[SetAnyag("+n+")]");
	}
	
	public int GetKopeny() {
		return kopenyVastagsag;
	}
	public void SetKopeny(int i) {
		kopenyVastagsag=i;
	}
	
	public List<Szomszéd> GetSzomszedok(){
		return this.szomszedok;
	}
	
	public void AddEntitas(Entitás e) {
		Main.printer.print("["+this+"].[AddEntitas("+e+")]");
		entitasok.add(e);
	}
	
	public void SetNapkozel(boolean b) {
		napkozel = b;
	}
	
	
	public Nyersanyag AnyagKinyeres() {
		return belsoAnyag;
	}
	
	public void Ledob(Entitás a) {
		Main.printer.print("["+this+"].Ledob("+a+")]");
	}
	
	public void Befogad(Entitás a) {
		Main.printer.print("["+this+"].[Befogad("+a+")]");
	}
	
	public void Napvihar() {
		Main.printer.print("[" + this + ".Napvihar()]");
		Main.printer.print(">Ureges az aszteroida? ('i' = igaz, 'h' = hamis)");
		Scanner in = new Scanner(System.in);
		String answer = in.nextLine();
		Main.printer.print(">Ertek: " + answer);
		if(answer.equals("i")) {
			Main.printer.print(">A Telepesek as a Robotok el tudtak bujni");
		}
		else {
			for(Entitás e: entitasok) {
				Main.printer.inc();
				e.Halal();
			}
		}
		Main.printer.dec();
		in.close();
	}
	
	public void SzomszedTorol(Szomszéd a) {
	}
	
	public void BazisEpit() {
	}
	
	public void KeregCsokken() {
		Main.printer.print("[" + this + ".KeregCsokken()]");
		kopenyVastagsag--;
		if(kopenyVastagsag == 0) {
			Main.printer.print(">Nem lehet tovabb furni");
		}
		Main.printer.dec();
	}
	
	public void Robban() {
		Main.printer.print("["+this+"].[Robban()]");
		Main.printer.inc();
		for (Entitás e : entitasok) {
			e.Felrobban();
		}
		Main.printer.dec();
		
	}
	
	public Szomszéd SzomszedotAd() {						//random szomszédot ad 
		Random rand = new Random();							//a szomszédok listából
		int randomNum = rand.nextInt(szomszedok.size());
		Main.printer.print("["+this+"].[SzomszedotAd()]");
		return szomszedok.get(randomNum);
	}
	
	public void Raktaroz(Nyersanyag a) {
		Main.printer.print("["+this+"].[Raktaroz(Nyersanyag a)]");
		belsoAnyag =a;
		if(napkozel) {
			Main.printer.inc();
			a.Napkozel(this);
		}
		Main.printer.dec();
	}
	
	public void AnyagTorol() {
	}
	public void SetSzomszed(Szomszéd a) {
		szomszedok.add(a);
	}

	public void SetKapu(Teleportkapu t) {
		kapuk.add(t);
	}
	public Szomszéd GetSzomszed(int n) {
		return szomszedok.get(n);
	}

	
}
