package szkeleton.game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Aszteroidaöv.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//




public class Aszteroidaöv {
	public void DoNapvihar() {
	}
	
	public void MinuszAszteroida(Aszteroida a) {
	}
}
