package szkeleton.game;

import java.util.List;
import java.util.Random;

//
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Aszteroida.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//




public class Aszteroida extends Szomszéd {
	private int kopenyVastagsag;
	private List<Teleportkapu> kapuk;
	private List<Entitás> entitasok;
	private List<Szomszéd> szomszedok;
	private Nyersanyag belsoAnyag;
	
	public Aszteroida() {
		kapuk=new List<Teleportkapu>();
		entitasok=new List <Entitás>();
		szomszedok=new List <Szomszéd>();
	}
	
	public void SetAnyag(Nyersanyag n) {
		belsoAnyag= n;
	}
	
	public int GetKopeny() {
		return kopenyVastagsag;
	}
	public void SetKopeny(int i) {
		kopenyVastagsag=i;
	}
	
	public List<Szomszéd> GetSzomszedok(){
		return this.szomszedok;
	}
	
	public void AddEntitas(Entitás e) {
		entitasok.add(e);
	}
	
	public Nyersanyag AnyagKinyeres() {
	}
	
	public void Ledob(Entitás a) {
	}
	
	public void Befogad(Entitás a) {
		System.out.println("Az entitás megérkezett az aszteroidára");
		a.SetAszteroida(this);											//beállítja az adott aszteroidát az entitásba
	}
	
	public void Napvihar() {
	}
	
	public void SzomszedTorol(Szomszéd a) {
	}
	
	public void BazisEpit() {
	}
	
	public void KeregCsokken() {
	}
	
	public void Robban() {
		System.out.println("Robban az aszteroida");
		for (Entitás e : entitasok) {
			e.Felrobban();
		}
		
	}
	
	public Szomszéd SzomszedotAd() {						//random szomszédot ad 
		Random rand = new Random();							//a szomszédok listából
		int randomNum = rand.nextInt(szomszedok.size());
		return szomszedok.get(randomNum);
	}
	
	public void Raktaroz(Nyersanyag a) {
	}
	
	public void AnyagTorol() {
	}
	
	
}
