package szkeleton.game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Entitás.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//

import java.util.Scanner;

public abstract class Entitás {
	private Aszteroidaöv jatekosok;
	protected Aszteroida aszteroida;
	public abstract void Mozgas(Szomszéd a);
	
	public Entitás() {
		Main.printer.print("[" + this + ".Entitas()]");
	}
	
	public void Furas() {
		Main.printer.print("[" + this + ".Furas()]" );
		Main.printer.inc();
		Main.printer.print(">Milyen vastag a kereg?");
		int num = Main.scanner.nextInt();
		Main.printer.print(">Ertek:" + num);
		if(num > 0) {
			Main.printer.inc();
			aszteroida.KeregCsokken();
		}
		Main.printer.dec();
		//Main.scanner.close();
		
	}
	
	public void SetAszteroida(Aszteroida a) {
		aszteroida=a;
	}
	
	public abstract void Halal();
	
	public abstract void Felrobban();
	
	public abstract void Lep();
}
