package szkeleton.game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Nyersanyag.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//




public abstract class Nyersanyag {
	private Aszteroida aszteroida;
	public abstract void Betolt(Telepes a);
	public abstract void Napkozel(Aszteroida a);
	public abstract boolean Kompatibilis(Nyersanyag ny);
}
