package szkeleton.game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Nyersanyag.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//




public abstract class Nyersanyag {
	private Aszteroida belsoAnyag;
	private Telepes nyersanyagok;
	
	public Nyersanyag() {
		Main.printer.print("[" + this + ".Nyersanyag()]");
		Main.printer.dec();
	}
	
	public abstract void Betolt(Telepes a);
	public abstract void Napkozel();
	public abstract boolean Kompatibilis(Nyersanyag ny);
}
