package szkeleton.game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Robot.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//

import java.util.List;
import java.util.Random;

public class Robot extends Entitás {
	
	public Robot() {
		Main.printer.print("["+this.toString()+"].[Robot()]");
		Main.printer.print("[" + this + ".Robot()]");
	}
	
	public void Mozgas(Szomszéd a) {
		Main.printer.print("["+this+"].[Mozgas("+a+")]");
	}
	
	public void Felrobban() {
		Main.printer.print("["+this+"].[Felrobban()]");
		Main.printer.inc();
		Szomszéd a= aszteroida.SzomszedotAd();		//random szomszédot kér
		this.aszteroida.Ledob(this);
		this.Mozgas(a);
		a.Befogad(this);
	}
	
	/**
	 * A Robot halálát intézõ függvény.
	 * @param Nincs átadott paramétere.
	 * @return Nincs visszatérési értéke.
	 */
	public void Halal() {
		Main.printer.print("[" + this + ".Halal()]");
		Main.printer.dec();	
	}
	
	public void Lep() {
	}
	
	@Override 
	public String toString() {
		return "Robot";
	}
	
}
