package szkeleton.game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Robot.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//

import java.util.List;
import java.util.Random;

public class Robot extends Entitás {
	public void Mozgas(Szomszéd a) {
		System.out.println("A robot mozog");
	}
	
	public void Felrobban() {
		System.out.println("A robot elrepül");
		Szomszéd a= aszteroida.SzomszedotAd();		//random szomszédot kér
		this.Mozgas(a);
		a.Befogad(this);
	}
	
	public void Halal() {
		Main.printer.print("[" + this + ".Halal()]");
		Main.printer.dec();	
	}
	
	public void Lep() {
	}
	
	
	
}
