package szkeleton.game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Szén.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//

import java.util.Scanner;

public class Szén extends Nyersanyag {
	
	/*public Szén() {
		Main.printer.print("["+this.toString()+ "].[Szén()]");
	}*/


	public Szén() {
		Main.printer.print("[" + this + ".Szen()]");
		Main.printer.dec();
	}
	
	public void Betolt(Telepes a) {
	}
	
	@Override
	public void Napkozel(Aszteroida a) {
		Main.printer.print("[" + this + ".Napkozel(a)]");
		Main.printer.dec();
	}
	
	/**
	 * A Nyersanyagok összehasonlítását végzõ függvény.
	 * @param A Nyersanyag, amivel össze kell hasonlítania önmagát.
	 * @return Egy logikai változó, ami megmondja, hogy ugyanolyan fajátjúak-e az összehasonlított Nyersanyagok.
	 */
	public boolean Kompatibilis(Nyersanyag ny) {
		Main.printer.print("[" + this + ".Kompatibilis(ny)]");
		Main.printer.print(">Megfelel a nyersanyag? ('i' = igaz, 'h' = hamis");
		//Scanner in = new Scanner(System.in);
		String answer = Main.scanner.nextLine();
		//in.close();
		if(answer.equals("i")) {
			Main.printer.dec();
			return true;
		}
		else {
			Main.printer.dec();
			return false;
		}
	}

	@Override 
	public String toString() {
		return "Szén";
	}

}
