package szkeleton.game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Szén.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//




public class Szén extends Nyersanyag {
	
	public Szén() {
		Main.printer.print("["+this.toString+ "].[Szén()]");
	}
	@Override 
	public String toString() {
		return "Szén;
	}
	public void Betolt(Telepes a) {
	}
	
	public void Napkozel(Aszteroida a) {
	}
	
	public boolean Kompatibilis(Nyersanyag ny) {
	}
	
	public void Betolt(Telepes a) {
	}
	
	public void Napkozel() {
	}
	
	public boolean Kompatibilis(Nyersanyag ny) {
	}
}
