package szkeleton.game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Telepes.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//




public class Telepes extends Entitás {
	public void Felrobban() {
		System.out.println("A telepes felrobban");
		Halal();
	}
	
	public void Mozgas(Szomszéd a) {
	}
	
	public void Banyaszat() {
	}
	
	public void Visszatolt() {
	}
	
	public Robot RobotEpit() {
	}
	
	public void KapuEpit() {
	}
	
	public void KapuLerak() {
	}
	
	public void BazisEpit() {
	}
	
	public void Halal() {
		System.out.println("A telepes meghal");
	}
	
	public void Lep() {
	}
	
	public void Mozgas(Szomszéd a) {
	}
	
	public void Halal() {
	}
	
	public void Felrobban() {
	}
	
	public void Lep() {
	}
}
