package szkeleton.game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Telepes.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

/**
 * @author
 *
 */
public class Telepes extends Entitás {
	
	private List<Teleportkapu> kapuk;
	private List<Nyersanyag> nyersanyagok;
	private Aszteroida aszteroida;
	
	public Telepes() {
		Main.printer.print("["+this.toString()+"].[Telepes()]");
		Main.printer.print("[" + this + ".Telepes()]");
		kapuk = new ArrayList<>();
		nyersanyagok = new ArrayList<>();
	}
	
	public void Felrobban() {
		Main.printer.print("["+this+"].[Felrobban()]");
		Main.printer.inc();
		Halal();
		Main.printer.dec();
	
	}
	
	public void Mozgas(Szomszéd a) {
	}
	
	public void Banyaszat() {
	}
	
	public void Visszatolt() {
		Main.printer.print("["+this+"].[Visszatolt()]");
		Main.printer.inc();
		aszteroida.Raktaroz(nyersanyagok.get(nyersanyagok.size()-1));
		nyersanyagok.remove(nyersanyagok.size()-1);
		Main.printer.dec();
	}
	
	public Robot RobotEpit() {
		Robot r = null;
		return r;
	}
	
	
	
	/**
	 * @param
	 * @return 
	 */
	public void KapuEpit() {
		Main.printer.print("[" + this + ".KapuEpit()]");
		Main.printer.inc();
		List<Nyersanyag> kell = new ArrayList<Nyersanyag>();
		Main.printer.inc();
		kell.add(new Urán());
		Main.printer.inc();
		kell.add(new Vas());
		Main.printer.inc();
		kell.add(new Vas());
		Main.printer.inc();
		kell.add(new Vízjég());
		Main.printer.inc();
		Útmutató tkapu = new Útmutató(kell);
		Main.printer.print(">Hany Uran van a Telepesnel?");
		Scanner in = new Scanner(System.in);
		int num = in.nextInt();
		for(int i = 0; i < num; i++) {
			if(nyersanyagok.size() <= 10) {
				Main.printer.inc();
				nyersanyagok.add(new Urán());
			}
		}
		Main.printer.print(">Hany Szen van a Telepesnel?");
		int sz = in.nextInt();
		for(int i = 0; i < sz; i++) {
			if(nyersanyagok.size() <= 10) {
				Main.printer.inc();
				nyersanyagok.add(new Szén());
			}
		}
		Main.printer.print(">Hany Vas van a Telepesnel?");
		int vas = in.nextInt();
		for(int i = 0; i < vas; i++) {
			if(nyersanyagok.size() <= 10) {
				Main.printer.inc();
				nyersanyagok.add(new Vas());
			}
		}
		Main.printer.print(">Hany Vizjeg van a Telepesnel?");
		int vj = in.nextInt();
		for(int i = 0; i < vj; i++) {
			if(nyersanyagok.size() <= 10) {
				Main.printer.inc();
				nyersanyagok.add(new Vízjég());
			}
		}
		int count = 0;
		for(Nyersanyag n : nyersanyagok) {
			Main.printer.inc();
			boolean answer = tkapu.MindMegvan(n);
			if(answer)
				count++;
		}
		if(count >= 4) {
			Main.printer.inc();
			Teleportkapu k1 = new Teleportkapu();
			Main.printer.inc();
			Teleportkapu k2 = new Teleportkapu();
			Main.printer.inc();
			kapuk.add(k1);
			Main.printer.inc();
			kapuk.add(k2);
			Main.printer.inc();
			k1.SetParja(k2);
			Main.printer.inc();
			k2.SetParja(k1);
		}
		else {
			Main.printer.print(">Nem epitheto teleportkapu");
		}
		Main.printer.dec();
	}
	
	public void KapuLerak() {
	}
	
	public void BazisEpit() {
	}
	
	public void Halal() {
		Main.printer.print("[" + this + ".Halal()]");   //A
		Main.printer.dec();								//A
	}
	
	public void Lep() {
	}
	
	public void AddNyersanyag(Nyersanyag ny) {
		nyersanyagok.add(ny);
		Main.printer.print("[" + this + "].AddNyersanyag("+ny+")");
	}
	@Override
	public String toString() { return "Telepes";} 
}
