package szkeleton.game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Telepes.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//

import java.util.List;

public class Telepes extends Entitás {
	
	private List<Teleportkapu> kapuk;
	private List<Nyersanyag> nyersanyagok;
	
	public Telepes() {
		Main.printer.print("["+this.toString()+"].[Telepes()]");
	}
	
	public void Felrobban() {
		Main.printer.print("["+this+"].[Felrobban()]");
		Main.printer.inc();
		Halal();
		Main.printer.dec();
	
	}
	
	public void Mozgas(Szomszéd a) {
	}
	
	public void Banyaszat() {
	}
	
	public void Visszatolt() {
	}
	
	//public Robot RobotEpit() {}
	
	
	public void KapuEpit() {
	}
	
	public void KapuLerak() {
	}
	
	public void BazisEpit() {
	}
	
	public void Halal() {
		Main.printer.print("[" + this + ".Halal()]");   //A
		Main.printer.dec();								//A
	}
	
	
	public void Lep() {
	}
	
	public void AddNyersanyag(Nyersanyag ny) {
		nyersanyagok.add(ny);
		Main.printer.print("[" + this + "].AddNyersanyag("+ny+")");
	}
	@Override
	public String toString() { return "Telepes";} 
}
