package szkeleton.game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Teleportkapu.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//




public class Teleportkapu extends Szomszéd {
	private Aszteroida aszteroida;
	private Teleportkapu parja;
	private Telepes kapuk;
	
	public Teleportkapu() {
		Main.printer.print("[" + this + ".Teleportkapu()]");
		Main.printer.dec();
	}
	
	public Aszteroida ParHelye() {
	}
	
	public void Robban() {
	}
	
	public void Befogad(Entitás a) {
	}
	
	public void SetParja(Teleportkapu tk) {
		Main.printer.print("[" + this + ".SetParja(k1)]");
		parja = tk;
		Main.printer.dec();
	}
}
