package szkeleton.game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Urán.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//

import java.util.Scanner;

public class Urán extends Nyersanyag {
	
	
	/*public  Urán() {
		Main.printer.print("["+this.toString()+"].[Urán()]");
	} */

	public Urán() {
		Main.printer.print("[" + this + ".Uran()]");
		Main.printer.dec();

	}
	
	public void Betolt(Telepes a) {
	}
	

	@Override
	public void Napkozel(Aszteroida a) {
		Main.printer.print("[" + this + "].Napkozel(a)");	
		Main.printer.inc();
		a.Robban();
		Main.printer.dec();
	}

	public void NapKozel(Aszteroida a) {
		Main.printer.print("["+this+"].NapKozel()");
		Main.printer.inc();
		a.Robban();
		Main.printer.dec();
	}
	
	public boolean Kompatibilis(Nyersanyag ny) {
		Main.printer.print("[" + this + ".Kompatibilis(ny)]");
		Main.printer.print(">Megfelel a nyersanyag? ('i' = igaz, 'h' = hamis)");
		//Scanner in = new Scanner(System.in);
		String answer = Main.scanner.nextLine();
		if(answer.equals("i")) {
			Main.printer.dec();
			return true;
		}
		else {
			Main.printer.dec();
			return false;
		}
	}
	
	@Override
	public String toString() {
		return "Urán";
	}
	
}
