package szkeleton.game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Urán.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//




public class Urán extends Nyersanyag {
	
	
	
	public  Urán() {
		Main.printer.print("["+this.toString()+"].[Urán()]");
	}
	
	public void Betolt(Telepes a) {
	}
	
	@Override
	public void Napkozel(Aszteroida a) {
		Main.printer.print("[" + this + "].Napkozel()");
		Main.printer.inc();
		
		a.Robban();
	}
	
	public boolean Kompatibilis(Nyersanyag ny) {
		return false;
	}
	@Override
	public String toString() {
		return "Urán";
	}
	
}
