package szkeleton.game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Vas.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//




public class Vas extends Nyersanyag {
	
	public Vas() {
		Main.printer.print("["+this.toString()+"].[Vas()]");
	}
	
	@Override
	public String toString() {
		return "Vas";
	}
	
	public void Betolt(Telepes a) {
	}
	
	public void Napkozel(Aszteroida a) {
	}
	
	public boolean Kompatibilis(Nyersanyag ny) {
	}
	
	public void Betolt(Telepes a) {
	}
	
	public void Napkozel() {
	}
	
	public boolean Kompatibilis(Nyersanyag ny) {
	}
}
