package szkeleton.game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Vas.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//

import java.util.Scanner;

public class Vas extends Nyersanyag {
	
	/*public Vas() {
		Main.printer.print("["+this.toString()+"].[Vas()]");
	}*/
	

	
	public void Betolt(Telepes a) {
	}

	public void Napkozel(Aszteroida a) {
		Main.printer.print("[" + this + ".Napkozel(a)]");
		Main.printer.dec();
	}

	public Vas() {
		Main.printer.print("[" + this + ".Vas()]");
		Main.printer.dec();

	}
	
	/**
	 * A Nyersanyagok összehasonlítását végzõ függvény.
	 * @param A Nyersanyag, amivel össze kell hasonlítania önmagát.
	 * @return Egy logikai változó, ami megmondja, hogy ugyanolyan fajátjúak-e az összehasonlított Nyersanyagok.
	 */
	public boolean Kompatibilis(Nyersanyag ny) {
		Main.printer.print("[" + this + ".Kompatibilis(ny)]");
		Main.printer.print(">Megfelel a nyersanyag? ('i' = igaz, 'h' = hamis)");
		Scanner in = new Scanner(System.in);
		String answer = in.nextLine();
		if(answer.equals("i")) {
			Main.printer.dec();
			return true;
		}
		else {
			Main.printer.dec();
			return false;
		}
	}
	
	@Override
	public String toString() {
		return "Vas";
	}
}
