package szkeleton.game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Vas.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//

import java.util.Scanner;

public class Vas extends Nyersanyag {
<<<<<<< HEAD
	
	public Vas() {
		Main.printer.print("["+this.toString()+"].[Vas()]");
	}
	
	@Override
	public String toString() {
		return "Vas";
	}
	
	public void Betolt(Telepes a) {
	}
=======
>>>>>>> branch 'main' of https://github.com/boriiza/Szkeleton.git
	
<<<<<<< HEAD
	public void Napkozel(Aszteroida a) {
	}
	
	public boolean Kompatibilis(Nyersanyag ny) {
=======
	public Vas() {
		Main.printer.print("[" + this + ".Vas()]");
		Main.printer.dec();
>>>>>>> branch 'main' of https://github.com/boriiza/Szkeleton.git
	}
	
	public void Betolt(Telepes a) {
	}
	
	public void Napkozel() {
	}
	
	public boolean Kompatibilis(Nyersanyag ny) {
		Main.printer.print("[" + this + ".Kompatibilis(ny)]");
		Main.printer.print(">Megfelel a nyersanyag? ('i' = igaz, 'h' = hamis");
		Scanner in = new Scanner(System.in);
		String answer = in.nextLine();
		if(answer.equals("i")) {
			Main.printer.dec();
			return true;
		}
		else {
			Main.printer.dec();
			return false;
		}
	}
}
