package szkeleton.game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Vízjég.java
//  @ Date : 2021. 03. 17.
//  @ Author : 
//
//

import java.util.Scanner;

public class Vízjég extends Nyersanyag {
	
	public Vízjég() {
		Main.printer.print("[" + this.toString() + ".Vizjeg()]");
		Main.printer.dec();
	}
	
	public void Betolt(Telepes a) {
	}
	
	/**
	 * A Nyersanyagok összehasonlítását végzõ függvény.
	 * @param A Nyersanyag, amivel össze kell hasonlítania önmagát.
	 * @return Egy logikai változó, ami megmondja, hogy ugyanolyan fajátjúak-e az összehasonlított Nyersanyagok.
	 */
	public boolean Kompatibilis(Nyersanyag ny) {
		Main.printer.print("[" + this + ".Kompatibilis(ny)]");
		Main.printer.print(">Megfelel a nyersanyag? ('i' = igaz, 'h' = hamis)");
		//Scanner in = new Scanner(System.in);
		String answer = Main.scanner.nextLine();
		if(answer.equals("i")) {
			Main.printer.dec();
			return true;
		}
		else {
			Main.printer.dec();
			return false;
		}
	}

	@Override
	public void Napkozel(Aszteroida a) {
		Main.printer.print("[" + this + ".Napkozel(a)]");
		a.AnyagTorol();
		Main.printer.dec();
	}

	@Override
	public String toString() {
		return "Vízjég";
	}

	
}
